name: main

on:
  - push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2.3.4
      - name: Setup node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.16.0
      - name: test
        run: make test
